//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MouldCalculator.Models
{
    using System;
    using System.Collections.Generic;
    using MouldCalculator.ViewModels;


    public partial class Component : BaseViewModel
    {
        private int _ComponentID;
        public int ComponentID { get => _ComponentID; set { _ComponentID = value; OnPropertyChanged(); } }

        private string _ComponentName;
        public string ComponentName { get => _ComponentName; set { _ComponentName = value; OnPropertyChanged(); } }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
